name = "llm-f"
version = "0.0.1"
license = "LGPL"
author = "Michael Voronov"
maintainer = "erg.sg@protonmail.com"

[dependencies]
neural-fortran = {git = "https://github.com/OneAdder/neural-fortran", branch = "llmf"}
